platform: linux
image_resource:
  type: docker-image
inputs:
  - name: gpdb_src  
  - name: python-tarball
outputs:
  - name: gpdb_artifacts
run:
  path: gpdb_src/concourse/scripts/compile_gpdb_oss.bash
params:  
  ORCA_TAG: v3.50.0
